### ISSUE TITLE
大佬song_type具体对应的歌曲类型能不能说明一下啊，文件都是数字

### ISSUE THREAD

**Issue by chinayuyabin** [yangjianxin1/QQMusicSpider#1]

**Comment by yangjianxin1** [comment]
@chinayuyabin 刚刚看了一下，发现url请求到的歌曲的type全是0，这个字段应该不是我们要的歌曲类型的字段，但其他字段不影响。

**Comment by chinayuyabin** [comment]
thx，我还以为是类似于下面的1：流行、6：嘻哈、2：摇滚、4：电子、3：民谣、8：R&amp;B、10：民歌、9：轻音乐、5：爵士、14：古典、25：乡村、20：蓝调




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yangjianxin1"<notifications@github.com&gt;; 
发送时间: 2019年12月26日(星期四) 晚上7:19
收件人: "yangjianxin1/QQMusicSpider"<QQMusicSpider@noreply.github.com&gt;; 
抄送: "@My heart will go on."<952167295@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [yangjianxin1/QQMusicSpider] 大佬song_type具体对应的歌曲类型能不能说明一下啊，文件都是数字 (#1)




@chinayuyabin 刚刚看了一下，发现url请求到的歌曲的type全是0，这个字段应该不是我们要的歌曲类型的字段，但其他字段不影响。

**Comment by yangjianxin1** [comment]
我一开始也以为是，没注意看，有空了我改改代码
