### ISSUE TITLE
song_type都是 0？

### ISSUE THREAD

**Issue by gongel** [yangjianxin1/QQMusicSpider#5]

**Comment by chichixdf** [comment]
这里的songtype并不是歌曲风格，你打印出来songInfo里的全部信息会发现，里面有一个genre字段，这个才是歌曲风格

**Comment by gongel** [comment]
> 这里的songtype并不是歌曲风格，你打印出来songInfo里的全部信息会发现，里面有一个genre字段，这个才是歌曲风格

thx
